### ISSUE TITLE
Suggestions: Change title color

### ISSUE THREAD

**Issue by fredydlemus** [fredydlemus/my_little_repo#1]
I think it looks better if the main title is a bit more orange

The styling rule could be change like this:

```css
h1 {
  color: #efa82e;
}
```
